# BROKEN: Healthcheck uses wrong username
version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: pg_health_lab
    environment:
      POSTGRES_USER: labuser
      POSTGRES_PASSWORD: labpass
      POSTGRES_DB: labdb
    ports:
      - "5433:5432"
    healthcheck:
      # BUG: wrong user in healthcheck — should be "labuser" not "wronguser"
      test: ["CMD-SHELL", "pg_isready -U wronguser -d labdb"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s
    restart: on-failure:5
