# BROKEN: ES JVM heap (1g) exceeds container memory limit (256m)
version: "3.8"

services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: es_debug_18_4
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      # BUG: JVM heap 1GB but container limited to 256MB
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9201:9200"
    deploy:
      resources:
        limits:
          memory: 256m
    restart: on-failure:3
